[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # Multi-key header rules are expressed with multi-line strings.
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

    # COMMENT: For sharedArrayBuffer, see https://developer.chrome.com/blog/enabling-shared-array-buffer/
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy =  "same-origin"
    # set CORP to cross-origin for anyone who wants to use the viewer in an iframe
    Cross-Origin-Resource-Policy = "cross-origin"
